#!/usr/bin/env bash
# LazyClaw Funnel watchdog — one check cycle (launchd fires this every
# STARTINTERVAL seconds; state lives in files so cycles are independent).
#
# Why this exists (2026-07-30 outage): when the Mac's LAN IP changes (router
# DHCP shuffle), the Tailscale Funnel session at the ingress goes stale while
# EVERY local signal keeps lying — BackendState Running, Health [], "Funnel
# on", certs issue fine, and the phone just reports "server not reachable".
# This watchdog curls the PUBLIC funnel URL (the same path the phone takes)
# and heals on sustained failure.
#
# There are TWO wedges, and the fix for one does nothing for the other
# (2026-08-21: this script retried mode A's fix for ~an hour against a mode-B
# failure and never recovered — a 3-minute outage became a 60-minute one):
#
#   A. host RESOLVES but HTTP fails — the ingress lost the node's tunnel
#      session. Fix: `serve reset` + re-register. `down`/`up` does NOT help.
#   B. host is NXDOMAIN — the funnel record was withdrawn from public DNS.
#      Fix: `down` + `up` to re-announce, then re-register. `serve reset`
#      does NOT help.
#
# So: diagnose by public DNS, apply the matching fix, and if it does not take,
# escalate to the other one immediately rather than waiting out the cooldown.
#
# Config: ~/.lazyclaw/funnel-watchdog.env (generated by the installer).
# Logs:   ~/.lazyclaw/funnel-watchdog.log
#
# Deliberately NOT `set -e`: a failing curl is the signal we exist to
# observe, not a reason to crash the cycle.
set -uo pipefail

LAZYCLAW_DIR="${HOME}/.lazyclaw"
ENV_FILE="${LAZYCLAW_DIR}/funnel-watchdog.env"
LOG_FILE="${LAZYCLAW_DIR}/funnel-watchdog.log"
FAILS_FILE="${LAZYCLAW_DIR}/funnel-watchdog.fails"
LAST_HEAL_FILE="${LAZYCLAW_DIR}/funnel-watchdog.last-heal"

[ -f "$ENV_FILE" ] || { echo "missing $ENV_FILE — run scripts/install-funnel-watchdog.sh" >&2; exit 1; }
# shellcheck source=/dev/null
source "$ENV_FILE"

: "${FUNNEL_URL:?FUNNEL_URL not set in $ENV_FILE}"
: "${FUNNEL_BACKEND:?FUNNEL_BACKEND not set in $ENV_FILE}"
CHECK_PATH="${CHECK_PATH:-/api/health}"
CHECK_TIMEOUT="${CHECK_TIMEOUT:-10}"
FAIL_THRESHOLD="${FAIL_THRESHOLD:-2}"
HEAL_COOLDOWN_SECS="${HEAL_COOLDOWN_SECS:-900}"
DRY_RUN="${DRY_RUN:-0}"

log() { printf '%s %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >> "$LOG_FILE"; }

# Cap the log so an unattended failure loop can't grow it unbounded.
if [ -f "$LOG_FILE" ] && [ "$(wc -c < "$LOG_FILE")" -gt 524288 ]; then
    tail -n 200 "$LOG_FILE" > "${LOG_FILE}.tmp" && mv "${LOG_FILE}.tmp" "$LOG_FILE"
fi

# Resolve the tailscale CLI (launchd's PATH is minimal).
TS_BIN="${TAILSCALE_BIN:-}"
[ -z "$TS_BIN" ] && TS_BIN="$(command -v tailscale || true)"
[ -z "$TS_BIN" ] && [ -x "/opt/homebrew/bin/tailscale" ] && TS_BIN="/opt/homebrew/bin/tailscale"
[ -z "$TS_BIN" ] && [ -x "/Applications/Tailscale.app/Contents/MacOS/Tailscale" ] \
    && TS_BIN="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
if [ -z "$TS_BIN" ]; then
    log "ERROR: tailscale CLI not found; cannot heal"
    exit 1
fi

http_code() { curl -s -m "$CHECK_TIMEOUT" -o /dev/null -w '%{http_code}' "$1" 2>/dev/null; }

public_code="$(http_code "${FUNNEL_URL}${CHECK_PATH}")"

if [ "$public_code" = "200" ]; then
    # Healthy. Log only a recovery transition, keep the steady state quiet.
    prev_fails="$(cat "$FAILS_FILE" 2>/dev/null || echo 0)"
    if [ "$prev_fails" != "0" ]; then
        log "recovered: public funnel healthy again (after ${prev_fails} failed checks)"
    fi
    echo 0 > "$FAILS_FILE"
    exit 0
fi

fails=$(( $(cat "$FAILS_FILE" 2>/dev/null || echo 0) + 1 ))
echo "$fails" > "$FAILS_FILE"
log "public check failed (code=${public_code:-none}, consecutive=${fails}/${FAIL_THRESHOLD})"

if [ "$fails" -lt "$FAIL_THRESHOLD" ]; then
    exit 0  # tolerate a transient blip; heal only on sustained failure
fi

# The funnel fronts a local backend — if THAT is down, re-registering the
# funnel fixes nothing and just churns. Different problem, different alarm.
backend_code="$(http_code "${FUNNEL_BACKEND}${CHECK_PATH}")"
if [ "$backend_code" != "200" ]; then
    log "backend ${FUNNEL_BACKEND} also unhealthy (code=${backend_code:-none}) — not a funnel wedge, skipping heal"
    exit 0
fi

# Cooldown: never re-register more than once per window, so a genuinely
# broken tailnet can't make us thrash the serve config every cycle.
now="$(date +%s)"
last_heal="$(cat "$LAST_HEAL_FILE" 2>/dev/null || echo 0)"
if [ $(( now - last_heal )) -lt "$HEAL_COOLDOWN_SECS" ]; then
    log "in heal cooldown ($(( now - last_heal ))s < ${HEAL_COOLDOWN_SECS}s), waiting"
    exit 0
fi

# ── Which failure mode? ────────────────────────────────────────────────────
#
# Two DIFFERENT wedges with two DIFFERENT fixes, and applying the wrong one
# accomplishes nothing (2026-08-21: this script retried mode-A's fix for ~an
# hour against a mode-B failure and never recovered). Public DNS tells them
# apart:
#
#   A. host RESOLVES, HTTP fails  → ingress lost the node's tunnel session.
#      Fix: serve reset + re-register. `down`/`up` does NOT help.
#   B. host is NXDOMAIN           → the funnel record was WITHDRAWN; the
#      control plane no longer has it registered. `serve reset` does NOT help.
#      Fix: down + up (re-announce), then re-register.
#
# Queried against a PUBLIC resolver, never the system one: the Mac runs
# MagicDNS, so the local resolver can answer for the tailnet even when the
# world can't see it — which is exactly the lie we're trying to detect.
funnel_host="$(printf '%s' "$FUNNEL_URL" | sed -E 's#^[a-z]+://##; s#[:/].*$##')"
dns_answer=""
if command -v dig >/dev/null 2>&1; then
    dns_answer="$(dig +short +time=4 +tries=1 @8.8.8.8 "$funnel_host" 2>/dev/null | head -1)"
elif command -v nslookup >/dev/null 2>&1; then
    dns_answer="$(nslookup "$funnel_host" 8.8.8.8 2>/dev/null | awk '/^Address: /{print $2; exit}')"
fi

if [ -n "$dns_answer" ]; then
    mode="A"; mode_desc="DNS resolves (${dns_answer}) — stale ingress session"
else
    mode="B"; mode_desc="NXDOMAIN — funnel record withdrawn"
fi

heal_serve() {
    log "  → serve reset + funnel --bg ${FUNNEL_BACKEND}"
    "$TS_BIN" serve reset >> "$LOG_FILE" 2>&1
    sleep 2
    "$TS_BIN" funnel --bg "$FUNNEL_BACKEND" >> "$LOG_FILE" 2>&1
    sleep 8
}

heal_reconnect() {
    # Re-announce the node to the control plane. --timeout so a tailnet that
    # genuinely needs interactive re-auth fails the cycle instead of hanging
    # launchd forever.
    log "  → down + up + funnel --bg ${FUNNEL_BACKEND}"
    "$TS_BIN" down >> "$LOG_FILE" 2>&1
    sleep 3
    "$TS_BIN" up --timeout=60s >> "$LOG_FILE" 2>&1
    sleep 5
    "$TS_BIN" funnel --bg "$FUNNEL_BACKEND" >> "$LOG_FILE" 2>&1
    sleep 10
}

if [ "$DRY_RUN" = "1" ]; then
    log "DRY_RUN: mode ${mode} (${mode_desc}) — would heal, then escalate if it didn't take"
    exit 0
fi

log "healing: mode ${mode} — ${mode_desc}"
echo "$now" > "$LAST_HEAL_FILE"

if [ "$mode" = "B" ]; then heal_reconnect; else heal_serve; fi

verify_code="$(http_code "${FUNNEL_URL}${CHECK_PATH}")"

# ESCALATE rather than wait out the cooldown. We have already paid the
# disruption of one heal; sitting in cooldown after a heal that plainly did
# not work is what turned a 3-minute outage into an hour-long one.
if [ "$verify_code" != "200" ]; then
    log "mode-${mode} heal did not take (code=${verify_code:-none}) — escalating"
    if [ "$mode" = "B" ]; then heal_serve; else heal_reconnect; fi
    verify_code="$(http_code "${FUNNEL_URL}${CHECK_PATH}")"
fi

if [ "$verify_code" = "200" ]; then
    log "heal SUCCEEDED — public funnel answering again"
    echo 0 > "$FAILS_FILE"
else
    log "heal FAILED after both strategies (code=${verify_code:-none}) — check the tailnet admin console (is Funnel still enabled for this node?)"
fi
